### ISSUE TITLE
Repo Description

### ISSUE THREAD

**Issue by dargmuesli** [mrVanDalo/memo#7]
"a simple memo tool ~wrote~ **written** in bash" pls <3

**Comment by mrVanDalo** [comment]
PR plz :D

**Comment by mrVanDalo** [comment]
I will fix it in the near future :+1:

**Comment by dargmuesli** [comment]
hell nah

![screenshot_2018-12-31 mrvandalo memo](https://user-images.githubusercontent.com/4778485/50562205-5ea5b000-0d12-11e9-802e-2692008d3ae5.png)

**Comment by mrVanDalo** [comment]
Happy ?

**Comment by dargmuesli** [comment]
New Year!
